### ISSUE TITLE
Page not found for every /cms endpoint

### ISSUE THREAD

**Issue by reSHARMA** [synfig/www.synfig.org#6]
The first Google Search result for synfig related stuff for me if from the endpoint /cms/en

![image](https://user-images.githubusercontent.com/16918004/48977810-8f694880-f0c7-11e8-8b16-f77923343e7d.png)

But they always end up to a page not found error.

![image](https://user-images.githubusercontent.com/16918004/48977818-ac9e1700-f0c7-11e8-83f1-a5de31e203a0.png)

Just try opening https://www.synfig.org/cms/en/support/

**Comment by morevnaproject** [comment]
now redirects to https://forums.synfig.org/. Thank you!
